version: "3.9"

services:
  vk-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
